Documenting failed update of dry-logic
The gem installed, however, when I ran:

```console
$ BUNDLE_GEMFILE=gemfiles/activesupport4-open.gemfile bundle exec rake
```

I got the following:

```console
NoMethodError:
  undefined method `curry' for #<Method: Module(Dry::Logic::Predicates::Methods)#type?>
```